### ISSUE TITLE
Restoring from model 

### ISSUE THREAD

**Issue by jchen98** [AdamByerly/BMCNNwHFCs#1]
Seems like there are some bugs in restoring from model at the moment. Specifically vars/bn/moving_mean_bn_conv_1/biased_2 does not seem to be saved to checkpoint.

![image](https://user-images.githubusercontent.com/6350132/80126463-222e4100-8561-11ea-8c08-55a1815d52c3.png)

**Comment by AdamByerly** [comment]
I'll take a look.  Are you trying to restore from a model while using the same --merge_strategy?  Model weight restoration in TensorFlow requires an identical graph, and different merge strategies result in different graphs.  Could you please share with me the parameters you set when launching the original run?

**Comment by jchen98** [comment]
Yup, I believe so! Yesterday night I ran this script:

```
python train.py --merge_strategy=2 --batch_size=120 --gpus=1 --trials=1
	--log_dir=../../data/learnable_ones_init/weights
	--data_dir=../../data/mnist_data --end_epochs=100

```

And this morning I ran this starting from the saved weights from epoch 6 

`python train.py --merge_strategy=2 --batch_size=120 --gpus=3 --trials=1 --log_dir=../../data/learnable_ones_init/weights --data_dir=../../data/mnist_data --start_epoch=7 --end_epoch=100 --weights_file=../../data/learnable_ones_init/weights/20200422223652/weights-6-best_loss-3000 --run_name=20200422223652 `

Aside from that, the only changes I made after cloning was to modify import python.training.<> to import <> to get train.py to run.

**Comment by AdamByerly** [comment]
It looks like you are trying to run on 3 GPUs on the second run, whereas the time before, it was only 1.  Since this model was created in TensorFlow graph mode, the GPU assignment is actually part of the graph.  Try restarting with only 1 GPU.

**Comment by jchen98** [comment]
Ah yes, that did it! Sorry for the trouble.

**Comment by AdamByerly** [comment]
No problem.
